language: python

python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "pypy"

install:
  - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install --use-mirrors argparse unittest2; fi
  - pip install -r requirements_dev.txt --use-mirrors
  - pip freeze
  - python setup.py install
  - sudo rm -rf /dev/shm && sudo ln -s /run/shm /dev/shm

script:
  - python -m covrun --pep8
  - sudo rm -rf pulsar
  - python -m covrun -w 4 --test-timeout 60

notifications:
  email: false

branches:
  only:
    - showpipfreeze
